service: product-service

frameworkVersion: '2'

useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  lambdaHashingVersion: 20201221

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  getProductsList:
    handler: src/functions/getProductsList/handler.main
    events:
      - http:
          method: get
          cors: true
          path: /products

  postProduct:
    handler: src/functions/postProduct/handler.main
    events:
      - http:
          method: post
          path: /products
          cors: true
          request:
            schemas:
              application/json: ${file(src/functions/postProduct/schema.json)}

  getProductsById:
    handler: src/functions/getProductsById/handler.main
    events:
      - http:
          method: get
          path: /products/{productId}
          cors: true
          request:
            parameters:
              paths:
                productId: true
