service: authorization-service

frameworkVersion: '2'

useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:REGION}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  lambdaHashingVersion: 20201221

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: src/functions/basicAuthorizer/handler.main

resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt:
          - BasicAuthorizerLambdaFunction
          - Arn
